### ISSUE TITLE
Frontend v2

### ISSUE THREAD

**Issue by menxit** [idena-dev/idena-pocket#5]
This is a branch born due the [amazing work](https://github.com/idena-dev/idena-pocket/pull/4) of @bingbinglee.

**Linked branch**: [frontend-v2](https://github.com/idena-dev/idena-pocket/tree/frontend-v2)

## Purposes
- General UI and UX improvements.
- Refactor of code

## Roadmap
- [X] general ui improvement @bingbinglee 
- [x] [manually refresh balance](https://github.com/idena-dev/idena-pocket/issues/3) @menxit 
- [x] [background refresh balance](https://github.com/idena-dev/idena-pocket/issues/2) @menxit 
- [x] [show async indicator while logging in](https://github.com/idena-dev/idena-pocket/issues/6) @menxit 
- [x] [show the pending transaction in transaction list](https://github.com/idena-dev/idena-pocket/issues/7) @menxit 
- [x] [last character from optional message is omitted](https://github.com/idena-dev/idena-pocket/issues/8) @menxit 
- [x] [show confirmation dialog when tapping / clicking reset](https://github.com/idena-dev/idena-pocket/issues/10) @menxit 
- [x] refactor of components and css @menxit 
- [x] [show "copied!" text on the UI somewhere when copy to clipboard returns true](https://github.com/idena-dev/idena-pocket/issues/9) @menxit 
- [X] bug fix: confirm seed with repeated word
- [X] use 512 as default chain_id derivation path (DnaMask support) @menxit
